name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  python-tests:
    name: Python • ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]  # Choisis 2 ou 3 versions comme demandé
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache poetry & pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock','**/pyproject.toml') }}

      - name: Install Poetry
        run: python -m pip install --upgrade pip && pip install poetry

      - name: Install dependencies
        run: |
          # Installer dans l'environnement du runner (evite virtualenv Poetry interne)
          poetry config virtualenvs.create false --local
          poetry install --no-interaction

      - name: Run unit tests
        run: |
          mkdir -p results
          poetry run pytest -q --junitxml=results/junit-${{ matrix.python-version }}.xml

      - name: Upload JUnit result
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-${{ matrix.python-version }}
          path: results/junit-${{ matrix.python-version }}.xml